image: node:10

stages:
  - .pre
  - build
  - test
  - testcafe
  - doc
  - package

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

install:
  stage: .pre
  only:
    - branches@SharePoint/sp-dev-fx-webparts/group-people
    - merge_requests
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /Update Changelog from CI/
  script:
    - npm i -g pnpm@5.18.9
    - pnpm i
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

coverage:
  stage: test
  needs: ["install"]
  dependencies: [install]
  only:
    - branches@SharePoint/sp-dev-fx-webparts/group-people
    - merge_requests
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /Update Changelog from CI/
  script:
    - npm test
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
      - jest
    reports:
      cobertura: jest/cobertura-coverage.xml
      junit:  junit.xml

testcafe_chrome:
  stage: testcafe
  needs: ["webpart"]
  dependencies: [webpart]
  only:
   - master@SharePoint/sp-dev-fx-webparts/group-people
   - dev@SharePoint/sp-dev-fx-webparts/group-people
  image: circleci/node:10-browsers
  environment:
    name: ltsrdev
  resource_group: ltsrdev
  script:
    - npm run testcafe:chrome
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
  artifacts:
    when: always
    paths:
      - testcafe_videos/**/*.mp4
      - testcafe_screenshots/**/*.png
    expire_in: 1 day
    reports:
      junit: ./testcafe_reports/*-junit.xml

testcafe_firefox:
  stage: testcafe
  # needs: ["webpart"]
  # dependencies: [webpart]
  # only:
  #  - master@SharePoint/sp-dev-fx-webparts/group-people
  #  - dev@SharePoint/sp-dev-fx-webparts/group-people
  image: circleci/node:10-browsers
  environment:
    name: ltsrdev
  resource_group: ltsrdev
  script:
    - npm run testcafe:firefox
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
  artifacts:
    when: always
    paths:
      - testcafe_videos/**/*.mp4
      - testcafe_screenshots/**/*.png
    expire_in: 1 day
    reports:
      junit: ./testcafe_reports/*-junit.xml

webpart:
  stage: build
  needs: ["install"]
  dependencies: [install]
  only:
    - master@SharePoint/sp-dev-fx-webparts/group-people
    - merge_requests
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /Update Changelog from CI/
  script:
    - npm run build
    - mv ./sharepoint/solution/group-people.sppkg ././group-people.sppkg
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
    - group-people.sppkg

pages:
  stage: doc
  needs: ["install"]
  dependencies: [install]
  only:
    - master@SharePoint/sp-dev-fx-webparts/group-people
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /Update Changelog from CI/
  script:
    - npm run doc
    - mkdir .public
    - cp -r ./docs/* .public
    - cp -r ./assets .public/
    - mv .public public
  cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
    - public

changelog:
  stage: package
  only:
    - master@SharePoint/sp-dev-fx-webparts/group-people
  script:
    - npm install -g conventional-changelog-cli && npm install -g version && apt-get install git
    - mkdir repo && cd ./repo
    - git clone -b $CI_COMMIT_REF_NAME https://gitlab-runner:$CI_ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git && git init &> /dev/null
    - cd ./$CI_PROJECT_NAME
    - conventional-changelog -p angular -i CHANGELOG.md -s && git add CHANGELOG.md && git pull
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git commit -m 'Update Changelog from CI' && git push origin $CI_COMMIT_REF_NAME &> /dev/null
  when: manual
