stages:
  - build
  - package

extension:
  image: node:8.15.0
  stage: build
  only:
    - tags
  script:
    - npm i -g gulp
    - npm i
    - npm audit fix
    - gulp bundle --ship
    - gulp package-solution --ship
    - mv ./sharepoint/solution/group-people.sppkg ././group-people.sppkg
  artifacts:
    paths:
    - group-people.sppkg
  allow_failure: false
